spring:
  application:
    name: franchise-cafe
  datasource:
    url: jdbc:mysql://localhost:3306/franchise-cafe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: cafe-admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:/db/migration.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        #        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

